### PR TITLE
build: adopt workspace dependencies

### PR DESCRIPTION
**Pull request by rvolosatovs**
# Feature or Problem

This simplifies maintenance of the repository and allows for easier audit of the dependencies

# Related Issues

Refs https://github.com/wasmCloud/wash/pull/389#discussion_r1107932984

# Release Information

# Consumer Impact

# Testing

Tested on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

## Platforms

Built on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### CODE REVIEW

**Review by brooksmtownsend — APPROVED** [review]
Just to be sure, when we release `wash-lib` it will be able to refer to the workspace dependencies even though it doesn't depend on `wash-cli`, right?

This makes a lot of sense 😄

**Comment by rvolosatovs** [comment]
> Just to be sure, when we release `wash-lib` it will be able to refer to the workspace dependencies even though it doesn't depend on `wash-cli`, right?
> 
> This makes a lot of sense smile

Yes, note that the crate is already a part of the workspace anyway.

You can verify this behavior via:
```
$ cd crates/wash-lib
$ cargo publish --dry-run
$ cat ../../target/package/wash-lib-0.6.0/Cargo.toml
```

Here's what the published `Cargo.toml` would look like:

```toml
# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO
#
# When uploading crates to the registry Cargo will automatically
# "normalize" Cargo.toml files for maximal compatibility
# with all versions of Cargo and also rewrite `path` dependencies
# to registry (e.g., crates.io) dependencies.
#
# If you are reading this file be aware that the original Cargo.toml
# will likely look very different (and much more reasonable).
# See Cargo.toml.orig for the original contents.

[package]
edition = "2021"
name = "wash-lib"
version = "0.6.0"
authors = ["wasmCloud Team"]
description = "wasmcloud Shell (wash) libraries"
readme = "README.md"
keywords = [
    "webassembly",
    "wasmcloud",
    "wash",
    "cli",
]
categories = [
    "wasm",
    "wasmcloud",
]
license = "Apache-2.0"
repository = "https://github.com/wasmcloud/wash"

[dependencies.anyhow]
version = "1.0.66"

[dependencies.async-compression]
version = "0.3"
features = [
    "tokio",
    "gzip",
]
default-features = false

[dependencies.cargo_toml]
version = "0.13.0"

[dependencies.clap]
version = "4"
features = [
    "derive",
    "env",
]
optional = true

[dependencies.command-group]
version = "1.0.8"
features = ["with-tokio"]

[dependencies.config]
version = "0.13.1"
features = ["toml"]
optional = true

[dependencies.console]
version = "0.15"
optional = true

[dependencies.dialoguer]
version = "0.10.2"
optional = true

[dependencies.dirs]
version = "4.0"

[dependencies.futures]
version = "0.3"

[dependencies.heck]
version = "0.4"
optional = true

[dependencies.ignore]
version = "0.4"
optional = true

[dependencies.indicatif]
version = "0.17.0"
optional = true

[dependencies.log]
version = "0.4"

[dependencies.nkeys]
version = "0.2.0"

[dependencies.oci-distribution]
version = "0.9.1"
features = ["rustls-tls"]
default-features = false

[dependencies.path-absolutize]
version = "3.0"
features = ["once_cell_cache"]
optional = true

[dependencies.provider-archive]
version = "0.6.0"

[dependencies.regex]
version = "1.5"
optional = true

[dependencies.reqwest]
version = "0.11"
features = [
    "json",
    "rustls-tls",
    "stream",
]
default-features = false

[dependencies.semver]
version = "1.0.12"
features = ["serde"]
optional = true

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true

[dependencies.serde_json]
version = "1.0.82"
optional = true

[dependencies.serde_with]
version = "2.0.0"

[dependencies.tempfile]
version = "3.2"

[dependencies.term-table]
version = "1.3.1"
optional = true

[dependencies.thiserror]
version = "1.0"

[dependencies.tokio]
version = "1"
features = ["process"]
default-features = false

[dependencies.tokio-stream]
version = "0.1"

[dependencies.tokio-tar]
version = "0.3"

[dependencies.toml]
version = "0.5"

[dependencies.walkdir]
version = "2.3"

[dependencies.wascap]
version = "0.9.2"

[dependencies.weld-codegen]
version = "0.6.0"

[dev-dependencies.claims]
version = "0.7.1"

[dev-dependencies.dirs]
version = "4.0"

[dev-dependencies.tempfile]
version = "3.2"

[dev-dependencies.test-case]
version = "2.2.1"

[dev-dependencies.tokio]
version = "1"
features = ["full"]
default-features = false

[features]
cli = [
    "clap",
    "term-table",
    "console",
    "dialoguer",
    "heck",
    "ignore",
    "indicatif",
    "path-absolutize",
    "regex",
]
default = [
    "start",
    "parser",
]
parser = [
    "config",
    "semver",
    "serde",
    "serde_json",
]
start = ["semver"]

[badges.maintenance]
status = "actively-developed"
```

**Comment by rvolosatovs** [comment]
> thread 'integration_up_can_start_wasmcloud_and_actor' panicked at 'assertion failed: output_to_string(start_echo).expect(\"could not retrieve output from echo start\").contains(\"Actor wasmcloud.azurecr.io/echo:0.3.4 started on host N\")', tests/integration_up.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test integration_up_can_start_wasmcloud_and_actor ... FAILED

> failures:

> failures:
>    integration_up_can_start_wasmcloud_and_actor

Does not appear to be caused by this PR. The test failure message is not too helpful and looks like the integration tests are using network, so it's bound to be flaky anyway

Any ideas on how to debug this? Maybe the tests should be just restarted?

**Review by ghost — APPROVED** [review]
This is great!

**Comment by ghost** [comment]
> > thread 'integration_up_can_start_wasmcloud_and_actor' panicked at 'assertion failed: output_to_string(start_echo).expect("could not retrieve output from echo start").contains("Actor wasmcloud.azurecr.io/echo:0.3.4 started on host N")', tests/integration_up.rs:59:5
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > test integration_up_can_start_wasmcloud_and_actor ... FAILED
> 
> > failures:
> 
> > failures:
> > integration_up_can_start_wasmcloud_and_actor
> 
> Does not appear to be caused by this PR. The test failure message is not too helpful and looks like the integration tests are using network, so it's bound to be flaky anyway
> 
> Any ideas on how to debug this? Maybe the tests should be just restarted?

Just a flake. #396 will help with fixing these

**Pull request merged**
