### PR TITLE
remove cargo dependency and add GitReference enum to git.rs

### LINKED ISSUE #279: [CHORE] Remove `cargo` dependency
We currently only use `cargo` for one struct, https://docs.rs/cargo/0.46.0/src/cargo/core/source/source_id.rs.html#63-70, `GitReference`, and I think we could just use our own version of this struct. 

This is all for an eventual goal of removing the openssl dependency for `wash`

### PR DESCRIPTION
**Pull request by ghost**
Fixes #279

Signed-off-by: Matt Wilkinson <mattwilki17@gmail.com>

### CODE REVIEW

**Comment by stevelr** [comment]
Looks good. Thanks!

**Review by stevelr — APPROVED** [review]

**Review by brooksmtownsend — APPROVED** [review]
Nice! I can see a path forward to ~no `rustls`~ 😄 

Edit: did a dumb, I meant no `openssl` and all the rustls :)

**Comment by ghost** [comment]
> Nice! I can see a path forward to no `rustls` 😄

OOTL: Why are we trying to drop `rustls`?

**Comment by brooksmtownsend** [comment]
Whoops, typo, corrected!

**Comment by ghost** [comment]
> Whoops, typo, corrected!

Ah lol. Had me confused!

**Pull request merged**
