### PR TITLE
Dockerfile missing shared object

### PR DESCRIPTION
**Pull request by jordan-rash**
Signed-off-by: Jordan Rash <15827604+jordan-rash@users.noreply.github.com>

### CODE REVIEW

**Comment by jordan-rash** [comment]
Currently 
```
╰─❯ docker run wasmcloud/wash:latest
Unable to find image 'wasmcloud/wash:latest' locally
latest: Pulling from wasmcloud/wash
336ecc4325b9: Pull complete
54e383b4b73d: Pull complete
83784763b038: Pull complete
b8a9186f7d84: Pull complete
687bb6cdfe08: Pull complete
15bb1cf4a8b6: Pull complete
b2139a9638c0: Pull complete
c96a7cc61b5b: Pull complete
Digest: sha256:3de67b39f58f37f47be32e87d73b18d019a9ac19848f9462414249e2d979bfa6
Status: Downloaded newer image for wasmcloud/wash:latest
Error loading shared library libz.so.1: No such file or directory (needed by /usr/local/bin/wash)
Error relocating /usr/local/bin/wash: deflateReset: symbol not found
Error relocating /usr/local/bin/wash: deflate: symbol not found
Error relocating /usr/local/bin/wash: deflateEnd: symbol not found
Error relocating /usr/local/bin/wash: crc32: symbol not found
Error relocating /usr/local/bin/wash: inflate: symbol not found
Error relocating /usr/local/bin/wash: inflateInit_: symbol not found
Error relocating /usr/local/bin/wash: deflateInit_: symbol not found
Error relocating /usr/local/bin/wash: inflateReset: symbol not found
Error relocating /usr/local/bin/wash: inflateEnd: symbol not found
```

**Review by autodidaddict — DISMISSED** [review]

**Review by brooksmtownsend — DISMISSED** [review]
LGTM and after #326 the integration test will pass 😄

**Comment by brooksmtownsend** [comment]
@jordan-rash This PR just needs a rebase since we had a bug in the integration test 😄

**Comment by jordan-rash** [comment]
> @jordan-rash This PR just needs a rebase since we had a bug in the integration test 😄

Done

**Review by brooksmtownsend — APPROVED** [review]

**Pull request merged**
