### PR TITLE
Initial wash up commit with command parsing

### PR DESCRIPTION
**Pull request by brooksmtownsend**
This commit implements a terminal UI for the wash REPL as well as command parsing within that REPL.

In order to accomplish this, I'm making use of a few crates:
- `tui` and `crossterm` for the alternate terminal UI
- `tui-logger` for the smart logger widget that allows for runtime log level selection
- `log` for easy log macros (debug!, info!, warn!, error!, trace!)
- `unicode-width` as a helper crate for cursor position

TODO for wash up implementation:
- [x] Clean up Structopt error / help text (some characters are not interpreted correctly)
- [x] Ensure edge cases are handled (for example, just passing the version flag in the REPL crashes the REPL without graceful exit)

This PR does not actually execute any of the commands in the REPL, it only provides help text and will log to the `info` level that it parsed the command successfully. Work to implement these commands will likely happen in the `lattice` module of this project, (potentially renamed to command interface), and then used in addition to creating a Host for the REPL to interact with.

Feedback welcome, you can install this version of `wash` with the following command to check out the UI:
```
cargo install wash-cli --git https://github.com/brooksmtownsend/wash --branch wash-up --force
```

### CODE REVIEW

**Review by autodidaddict — CHANGES_REQUESTED** [review]
This is likely stuff you're already working on, but:

* When I tab over to the smart widget and select a log, it doesn't change the output
* I can't scroll the log output on the right side log collector
* When I type "help" it comes back as red error rather than a supported command
* I can't type quit, cancel, logout, helpme-i-cant-escape or anything else

super ultra nitpick - if you put a leading and trailing space on the names of the 3 different widgets, it looks a little nicer as it adds a little buffer between the text and the ASCII lines.

**Comment by brooksmtownsend** [comment]
> This is likely stuff you're already working on, but:
> 
> * When I tab over to the smart widget and select a log, it doesn't change the output
> * I can't scroll the log output on the right side log collector
> * When I type "help" it comes back as red error rather than a supported command
> * I can't type quit, cancel, logout, helpme-i-cant-escape or anything else
> 
> super ultra nitpick - if you put a leading and trailing space on the names of the 3 different widgets, it looks a little nicer as it adds a little buffer between the text and the ASCII lines.

All great feedback, and the get-me-out-of-here command you're looking for is `exit` 😛  It's displayed in the `help` text, but I'm open to a name change

**Comment by autodidaddict** [comment]
It should support exit， quit, and maybe ":q!" 😄😁

**Comment by brooksmtownsend** [comment]
Hm maybe we should be just like vim, only support :q! and trap our users. 🤔

**Comment by brooksmtownsend** [comment]
Marked as do-not-merge as I'd like this PR to implement the `up` command entirely.
In the last commit, @autodidaddict , I was able to address a few issues:
- Quit now recognizes 'quit', 'exit', 'q', 'logout' and ':q!'
- Help is now correctly flagged as an `info` level log 
Working on the other comments now, some of them may be issues with the logger widget that aren't in my control

**Comment by brooksmtownsend** [comment]
Also the build is failing because of `wasmcloud` renames, woo. Planning to fix that up once the repo is fully renamed

**Comment by autodidaddict** [comment]
Is this still a WIP?

**Comment by brooksmtownsend** [comment]
@autodidaddict It might be best to merge this in, I was waiting to hook it up to the command interface but the initial commit is solid. I'll fix up the merge conflicts and push

**Comment by brooksmtownsend** [comment]
@autodidaddict @billyoung Merged in the latest from `main`. I've added the two remaining concerns:
- When I tab over to the smart widget and select a log, it doesn't change the output
- I can't scroll the log output on the right side log collector

To the issue for implementation: https://github.com/wasmCloud/wash/issues/18

Any other concerns?

**Comment by autodidaddict** [comment]
> Any other concerns?

None that should delay the merging of this. We haven't released wash yet, so I'm fine with discovering more tweaks as we go. We'll need road time actually using the CLI and the REPL to figure out what needs adjustment.

**Review by autodidaddict — APPROVED** [review]

**Pull request merged**
