### PR TITLE
mac fixes + remove debugging code

### PR DESCRIPTION
**Pull request by stevelr**
fixes new actor/interface/project on macos
fixes test build on macos
remove debugging code

Signed-off-by: stevelr <steve@cosmonic.com>

### CODE REVIEW

**Review by autodidaddict — DISMISSED** [review]
I'm assuming that this has been tested/vetted on a Mac. Let me know if you want me to double-check this on my M1 mac. Otherwise LGTM.

**Comment by autodidaddict** [comment]
@stevelr looks like this failed the `fmt` check. Classic.

**Comment by stevelr** [comment]
apparently my mac dev environment isn't fully updated: example - the rustfmt errors and the github signature  -Can someone else please check on macos?  thanks. M1 vs x86 shouldn't make a difference since it's an OS file path issue.

**Review by brooksmtownsend — APPROVED** [review]
worked on my mac 👍🏻

**Pull request merged**
