### PR TITLE
release(wash-lib): v0.6.1

### PR DESCRIPTION
**Pull request by vados-cosmonic**
## Feature or Problem
Release `wash-lib` v0.6.1 and bump dependency in `wash`

## Related Issues

Contains fix for #341 (issues with dashed names in actors)

## Release Information

`wash-lib` `0.6.1`

## Consumer Impact

Consumers will be able to create actors with dashes in their names where that previously caused failures during build.

## Testing

Built on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

N/A

### Acceptance or Integration

N/A

### Manual Verification

Manually verified locally

### CODE REVIEW

**Comment by vados-cosmonic** [comment]
@brooksmtownsend  @mattwilkinsonn Recreated [the other PR](https://github.com/wasmCloud/wash/pull/448) since it was misnamed (and `wash` has merge commits), didn't want the `0.7.0` branch name to be in the history.

**Review by ghost — CHANGES_REQUESTED** [review]
Actually looking at this again I think we should also bump `wash-cli` to `0.16.1` at the same time

**Comment by vados-cosmonic** [comment]
@mattwilkinsonn oh you're totally right -- just added it, thank you

**Comment by ghost** [comment]
The rebase here is a little messed up - it's showing my changes from #445 again. Might want to just checkout a fresh branch from a synced `main` and commit the changes to that

**Comment by vados-cosmonic** [comment]
Yeah I don't know why it did that -- I did checkout a fresh branch but the order is still showing up weird... I'll re-clone all together

**Pull request closed without merging**
