### PR TITLE
Always clean up test directories in `integration_par` and add extra assert for the `reg pull`.

### PR DESCRIPTION
**Pull request by ghost**
Related to #405.

Signed-off-by: Matt Wilkinson <matt@mattwilkinson.dev>

### CODE REVIEW

**Comment by autodidaddict** [comment]
This is likely a matter of personal language preference, but the `defer!` macro feels like it has the potential to confuse readers who have experience with different languages, namely Go. Not everyone is going to know what it does or how it works on a quick glance, or that it works differently than Go's defer, which makes people like me more likely to use it the wrong way 😁 

Is there something more idiomatically "Rusty" that we can do here instead like implementing `Drop` or maybe there's a hook we can use to attach into the Rust test runner?

**Comment by ghost** [comment]
> This is likely a matter of personal language preference, but the `defer!` macro feels like it has the potential to confuse readers who have experience with different languages, namely Go. Not everyone is going to know what it does or how it works on a quick glance, or that it works differently than Go's defer, which makes people like me more likely to use it the wrong way 😁
> 
> Is there something more idiomatically "Rusty" that we can do here instead like implementing `Drop` or maybe there's a hook we can use to attach into the Rust test runner?

Agreed 100%. All my homies hate `defer!` and macros in general. I'm just trying to fix these flakes quickly because they are becoming a huge blocker, I'll go and refactor to use `Drop` or `tempfile::TempDir` later

**Review by thomastaylor312 — DISMISSED** [review]
@mattwilkinsonn Let's create an issue so we don't forget to follow up on the defer stuff

**Comment by ghost** [comment]
> @mattwilkinsonn Let's create an issue so we don't forget to follow up on the defer stuff

I updated #405 to reflect this, it's kinda two steps of the same thing. I think I cause too much issue pollution in this repo anyways lol

**Comment by ghost** [comment]
Updated to use `tempfile::TempDir` in everywhere except the cached artifact test, which relies on the directory we use being `/tmp/wasmcloud_ocicache` exactly, so I needed to keep the `defer!`

**Comment by brooksmtownsend** [comment]
Gonna close this one since it's getting a little stale, but feel free to re-open if we can get the conflict fixed and we can agree on the defer stuff

**Pull request closed without merging**
