### PR TITLE
Support provider configuration json for start

### PR DESCRIPTION
**Pull request by brooksmtownsend**
Signed-off-by: Brooks Townsend <brooks@cosmonic.com>

### CODE REVIEW

**Review by autodidaddict — APPROVED** [review]

**Comment by thomastaylor312** [comment]
Is this a breaking change? Seems more like a new feature

**Comment by autodidaddict** [comment]
The feature has been part of the control interface for quite some time... wash just didn't support specifying it (it was explicitly forcing provider startup configuration to `None`)

**Comment by thomastaylor312** [comment]
Ok, going to remove the breaking label then

**Comment by stevelr** [comment]
Is this a machine-generated config or hand-generated? for hand-generated, some of us prefer toml over json. Capability provider configs and codegen are usually toml files. It it's machine generated, slight preference for json.

**Comment by autodidaddict** [comment]
it depends entirely on the provider. It's an opaque **json** string by convention. Each provider has the power to do with this string as they please. But, on the wire, we just treat it like a string.

**Pull request merged**
