### PR TITLE
add tinygo actor template

### PR DESCRIPTION
**Pull request by stevelr**
Signed-off-by: stevelr <steve@cosmonic.com>

### CODE REVIEW

**Comment by stevelr** [comment]
also fixes some directory manipulation to make it easier to perform local testing

**Review by autodidaddict — APPROVED** [review]

**Review by brooksmtownsend — COMMENTED** [review]
Looks great, though I worry now that our github actions to build/release actors now have to be language specific 🤔 We may just need to prioritize https://github.com/wasmCloud/wash/issues/263 appropriately in order to build actors in a language-agnostic way

**Comment by stevelr** [comment]
@brooksmtownsend I don't think this is a problem:
- we don't have a `wash build` command , so that's not an issue (yet).
- Codegen _is_ language specific - if you run `wash gen` it reads codegen.toml, which has language-specific sections in it.
- As far as building, for now we just use `make` to build the actor, and they show up in `build/actor_s.wasm`. The makefile should do the right thing.

- we can't do `rustfmt` automatically - for that we'd have to check for the presence of Cargo.toml - (which itself should be inside a common action script).  Or, alternately, use `make test` to run tests or `make check` to check formatting.

**Comment by stevelr** [comment]
This doesn't strictly depend on code generation, so I'll merge now ...

**Comment by brooksmtownsend** [comment]
> As far as building, for now we just use make to build the actor, and they show up in build/actor_s.wasm. The makefile should do the right thing.

Duh! Good point. I may test this once we get everything merged and can make any necessary adjustments to the actions

**Pull request merged**
