### PR TITLE
Bug build actor cargo workspace #wasm cloud/wash/446

### PR DESCRIPTION
**Pull request by lee-orr**
## Feature or Problem

Actors can't build if they are in a workspace. This allows the build to get the accurate workspace target folder, if no folder is given as a parameter - enabling building actors within a workspace without needing to adjust any other aspects of the build process.

## Related Issues

#446

## Consumer Impact

this should only affect consumers using the build command without specifying a specific target directory, who are within a workspace.

## Testing

Added an integration test for building a rust actor in a workspace

Built on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [x] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Acceptance or Integration

build_rust_actor_in_workspace_unsigned in integration_build.rs

### Manual Verification

Tested on a local actor in a workspace

### CODE REVIEW

**Review by brooksmtownsend — APPROVED** [review]
Thank you for this @lee-orr ! Great to get this working in a workspace. You might need a rebase on `main` since I merged your devcontainer PR, but then this should be good to go

**Comment by lee-orr** [comment]
> Thank you for this @lee-orr ! Great to get this working in a workspace. You might need a rebase on `main` since I merged your devcontainer PR, but then this should be good to go

I fixed the merge issue, but for some reason it seems to have pulled in all my commits from the other PR... I'm not sure why that is.

**Comment by brooksmtownsend** [comment]
>I fixed the merge issue, but for some reason it seems to have pulled in all my commits from the other PR... I'm not sure why that is.

This might just be a `git` thing, it might be a little harder now because of the merge commits but you can try fetching from upstream and rebasing.

Assuming you have `wasmCloud` saved as `upstream`, this should do the trick. If you hit merge conflicts you can either step through them or let me know and run `git rebase --abort`. 
```
git fetch upstream
git rebase upstream/main
```

**Comment by lee-orr** [comment]
rebase should be done

**Review by brooksmtownsend — APPROVED** [review]
Looks like the rebase kinda worked, I'll squash when merging to ensure it's just one commit

**Review by brooksmtownsend — APPROVED** [review]
Looks like the rebase kinda worked, I'll squash when merging to ensure it's just one commit

**Pull request merged**
